restructured to support add ons

diff --git a/build b/build
--- a/build
+++ b/build
@@ -26,86 +26,80 @@
 
 # Global variables
 FILE=${0##*/}
-OPTIONS=composer,help,logentries,memcache,ssl,varnish,version
-PATH=$(readlink -f $0)
-VERSION=2.0.0
+VERSION=3.0.0
 
 # Parse options
-ARGS=$(/usr/bin/getopt -o hv -l $OPTIONS -n $FILE -- "$@")
+ARGS=$(/usr/bin/getopt -o hv -l addons:,help,verion -n $FILE -- "$@")
 eval set -- "$ARGS"
 
 # Loop options and set flags
 while true; do
     case $1 in
-        --composer)   COMPOSER=TRUE;;
-        --logentries) LOGENTRIES=TRUE;;
-        --memcache)   MEMCACHE=TRUE;;
-        --ssl)        SSL=TRUE;;
-        --varnish)    VARNISH=TRUE;;
+        --addons)     shift
+                      ADDONS=$1;;
+        -v|--version) echo "$VERSION"
+                      exit 0;;
         -h|--help)    echo "Usage: $FILE [options] 
        $FILE --version
 
-Convert AMI instance from Apache to Nginx/PHP-FPM. Optional support for Composer, rsyslogging, Memcache, SSL and Varnish.
-        
+Convert AMI instance from Apache to Nginx/PHP-FPM. With support for deployment hooks, Varnish and more through addon packages    
 
 Options:
-  --composer    install Composer, Dependency Manager for PHP
+  --addons      comma seperated list of addons to install
   -h|--help     show this output
-  --logentries  enable rsyslogging to logentries
-  --memcache    enable memcache support
-  --ssl         enable ssl
-  --varnish     install Varnish as a reserve proxy
-  -v|--version show version information
+  -v|--version  show script version
 "
                       exit 0;;
-        -v|--version) echo "$VERSION" exit 0;;
         *)            break;;
     esac 
     shift
 done
 
 # Output header
-echo ''
-echo '# AWS Elastic Beanstalk Nginx/PHP-FPM Configuration'
-echo '# Copyright 2012 Carbon Coders Ltd'
-echo ''
-if [ $COMPOSER ]; then
-    echo 'Composer: Yes'
+echo -e '# AWS Elastic Beanstalk Nginx/PHP-FPM Configuration\n# Copyright 2012 Carbon Coders Ltd'
+if [[ $ADDONS ]]; then
+    echo -e "# $ADDONS\n"
+    ADDONS=${ADDONS},
+    IFS=','
 else
-    echo 'Composer: No'
-fi
-if [ $LOGENTRIES ]; then
-    echo 'Logentries: Yes'
-else
-    echo 'Logentries: No'
-fi
-if [ $MEMCACHE ]; then
-    echo 'Memcache: Yes'
-else
-    echo 'Memcache: No'
-fi
-if [ $SSL ]; then
-    echo 'SSL: Yes'
-else
-    echo 'SSL: No'
-fi
-if [ $VARNISH ];  then
-    echo 'Varnish: Yes'
-else
-    echo 'Varnish: No'
+    echo -e '# No addons\n'
 fi
 /bin/sleep 5
 
-# Remove unneeded packages
-echo ''
+# Download files and folders
+echo "Downloading build files and folders"
+/bin/rm -rf /tmp/build
+/usr/bin/git clone git://github.com/carboncoders/elasticbeanstalk-nginx-php.git /tmp/build > /dev/null 2>&1
+if [ ! -f '/tmp/build/build' ]; then
+    echo 'Error downloading main folders'
+    exit 1
+fi
+
+# Loop comma seperated options
+if [[ $ADDONS ]]; then
+    for ADDON in $ADDONS; do
+
+        # Clone GIT URL
+        if [ ${ADDON:0:6} = 'git://' ]; then
+            PATH=${ADDON////.}
+            /usr/bin/git clone $ADDON /tmp/build/addons/$PATH > /dev/null 2>&1
+            ADDON=$PATH
+        fi
+
+        # Check folder exists
+        if [ ! -f "/tmp/build/addons/$ADDON/build" ]; then
+            echo "Unable to locate addon: $ADDON"
+            exit 1
+        fi
+    done
+fi
+
+# Remove packages
 echo 'Removing unneeded packages'
-/bin/sleep 5
-/usr/bin/yum -q -y remove httpd* nginx* php*
+/usr/bin/yum -q -y remove httpd* nginx* php* > /dev/null 2>&1
 
 # Install Nginx
-echo ''
 echo 'Installing Nginx'
-/bin/sleep 5
 /usr/bin/yum -q -y install nginx
 if [ $? -ne 0 ]; then
     echo 'Error trying to install Nginx'
@@ -113,153 +107,50 @@ if [ $? -ne 0 ]; then
 fi
 /bin/rm -rf /etc/nginx/conf.d/*
 
-# Install Varnish
-if [ $VARNISH ]; then
-    echo ''
-    echo 'Installing Varnish'
-    /bin/sleep 5
-    /usr/bin/yum -q -y install varnish
-    if [ $? -ne 0 ]; then
-        echo 'Error trying to install Varnish'
-        exit 1
-    fi
-fi
-
 # Install PHP 5.4 (with httpd 2.4 as dependency)
-echo ''
 echo 'Installing PHP 5.4 with FPM'
-/bin/sleep 5
 /usr/bin/yum -q -y install php54* --exclude=php54-mysqlnd
 if [ $? -ne 0 ]; then
     echo 'Error trying to install PHP'
     exit 1
 fi
 
-# Install Memcache
-if [ $MEMCACHE ]; then
-    echo ''
-    echo 'Installing Memcache'
-    /bin/sleep 5
-    /usr/bin/yum -q -y install memcached
-    if [ $? -ne 0 ]; then
-        echo 'Error trying to install Memcache'
-        exit 1
-    fi
-fi
+# Merge folders
+echo 'Merging main folders'
+/bin/cp -rf /tmp/build/etc /
+/bin/cp -rf /tmp/build/opt /
 
-# Install Composer
-if [ $COMPOSER ]; then
-    echo ''
-    echo 'Installing Composer'
-    /bin/sleep 5
-    /usr/bin/curl -s http://getcomposer.org/installer | /usr/bin/php
-    if [ ! -f 'composer.phar' ]; then
-        echo 'Error downloading Composer'
-        exit 1
-    fi
-    /bin/mv composer.phar /usr/bin/composer
+# Install addons
+if [[ $ADDONS ]]; then
+    for ADDON in $ADDONS; do
+
+        # Correct addon path
+        if [ ${ADDON:0:6} = 'git://' ]; then
+            ADDON=${ADDON////.}
+        fi
+
+        # Run addon build
+        /bin/bash /tmp/build/addons/$ADDON/build
+        if [ $? -ne 0 ]; then
+            echo "Addon returned error: $ADDON"
+            exit 1
+        fi
+    done
 fi
 
 # Updating packages
-echo ''
 echo 'Updating packages'
-/bin/sleep 5
 /usr/bin/yum -q -y update
 
-# Download files and folders
-echo ''
-echo "Downloading build files and folders"
-/bin/sleep 5
-/bin/rm -rf /tmp/build
-/usr/bin/git clone git://github.com/carboncoders/elasticbeanstalk-nginx-php.git /tmp/build
-
-# Check download was successful
-if [ ! -f '/tmp/build/build' ]; then
-    echo 'Error downloading folders'
-    exit 1
-fi
-
-# Alter nginx config for varnish
-if [ $VARNISH ]; then
-    /bin/sed -i "110i\    listen 8080;" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-fi
-
-# Install SSL
-if [ $SSL ]; then
-    echo ''
-    echo 'Generating SSL certificate and modifying nginx startup script'
-    /bin/sleep 5
-    /usr/bin/openssl genrsa -des3 -passout pass:1234 -out /etc/ssl/certs/server.key 1024
-    /usr/bin/openssl req -new -config /tmp/build/ssl/openssl.cnf -passin pass:1234 -key /etc/ssl/certs/server.key -out /etc/ssl/certs/server.csr
-    /bin/mv -f /etc/ssl/certs/server.key /etc/ssl/certs/server.key.org
-    /usr/bin/openssl rsa -passin pass:1234 -in /etc/ssl/certs/server.key.org -out /etc/ssl/certs/server.key
-    /usr/bin/openssl x509 -req -days 365 -in /etc/ssl/certs/server.csr -signkey /etc/ssl/certs/server.key -out /etc/ssl/certs/server.crt
-    /bin/rm -f /etc/ssl/certs/server.key.org /etc/ssl/certs/server.csr
-    if [ ! -f '/etc/ssl/certs/server.crt' ]; then
-        echo 'Error generating self-signed SSL certificate'
-        exit 1
-    fi
-
-    # INCEPTION!
-    /bin/sed -i "148c\          log('Nginx server configuration file failed to be written', :critical, [ :nginx ]) unless ::File.exists?('/etc/nginx/conf.d/server.conf')" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-    /bin/sed -i "149i\ " /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-    /bin/sed -i "150i\          # copy nginx server.conf to ssl.conf and add the necessary lines to enable ssl" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-    /bin/sed -i "151i\          \`/usr/bin/sudo cp -f /etc/nginx/conf.d/server.conf /etc/nginx/conf.d/ssl.conf\`" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-    /bin/sed -i "152i\          \`/usr/bin/sudo sed -i '/^\s*listen/ d' /etc/nginx/conf.d/ssl.conf\`" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb # delete the listen 8080; command if there
-    /bin/sed -i "153i\          \`/usr/bin/sudo sed -i '28i\    listen 443 default_server ssl;' /etc/nginx/conf.d/ssl.conf\`" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-    /bin/sed -i "154i\          \`/usr/bin/sudo sed -i '29i\    ssl_certificate \/etc\/ssl\/certs\/server.crt;' /etc/nginx/conf.d/ssl.conf\`" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-    /bin/sed -i "155i\          \`/usr/bin/sudo sed -i '30i\    ssl_certificate_key \/etc\/ssl\/certs\/server.key;' /etc/nginx/conf.d/ssl.conf\`" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-    /bin/sed -i "156i\          log('Nginx ssl configuration file failed to be written', :critical, [ :nginx ]) unless ::File.exists?('/etc/nginx/conf.d/ssl.conf')" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-    /bin/sed -i "157i\ " /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
-fi
-
-# Set up log forwarding
-if [ $LOGENTRIES ]; then
-    # Install rsyslog-gnutls to support rsyslog forwarding using TLS
-    echo ''
-    echo 'Setting up rsyslog fowarding for logentries'
-    /bin/sleep 5
-    /usr/bin/yum -q -y install rsyslog-gnutls
-
-    /bin/sed -i "46i\ " /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/applications/phpapplication.rb
-    /bin/sed -i "47i\          HostManager.log 'Updating Logentries options'" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/applications/phpapplication.rb
-    /bin/sed -i "48i\          ElasticBeanstalk::HostManager::Utils::LogentriesUtil.update_logentries_conf(ElasticBeanstalk::HostManager.config.application['Environment Properties'])" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/applications/phpapplication.rb
-    /bin/sed -i "26i\require 'elasticbeanstalk/hostmanager/utils/logentriesutil'" /tmp/build/opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/init-php.rb
-fi
-
-# Merge folders
-echo ''
-echo 'Merging folders'
-/bin/cp -rf /tmp/build/etc /
-/bin/cp -rf /tmp/build/opt /
-if [ $VARNISH ]; then
-    /bin/cp -rf /tmp/build/varnish/etc /
-    /bin/cp -rf /tmp/build/varnish/opt /
-fi
-if [ $LOGENTRIES ]; then
-    /bin/cp -rf /tmp/build/logentries/etc /
-    /bin/cp -rf /tmp/build/logentries/opt /
-fi
-
 # Take ownership
-echo ''
 echo 'Correcting permissions'
-/bin/sleep 5
 /bin/chown -R elasticbeanstalk:elasticbeanstalk /etc/nginx/conf.d \
                                                 /opt/elasticbeanstalk \
                                                 /var/log/nginx \
                                                 /var/log/php-fpm
-if [ $COMPOSER ]; then
-    /bin/chown -R elasticbeanstalk:elasticbeanstalk /usr/bin/composer
-fi
-if [ $LOGENTRIES ]; then
-    /bin/chown -R elasticbeanstalk:elasticbeanstalk /etc/rsyslog.d
-fi
 
 # Clear unneeded files
-echo ''
 echo 'Clearing unneeded files'
-/bin/sleep 5
 /bin/rm -rf /etc/httpd \
             /opt/elasticbeanstalk/var/log/* \
             /tmp/build \
@@ -269,15 +160,11 @@ echo 'Clearing unneeded files'
 
 # Clear autostarts
 echo 'Clearning autostarts'
-/bin/sleep 5
 /sbin/chkconfig nginx off
 /sbin/chkconfig php-fpm off
-if [ $VARNISH ]; then
-    /sbin/chkconfig varnish off
-fi
 
 # End script
 echo 'Successfully built!'
-/bin/rm -f $PATH
+/bin/rm -f $(readlink -f $0)
 history -c
 exit 0
